### ISSUE TITLE
main.tex file is empty

### ISSUE THREAD

**Issue by nai888** [LLBlumire/recursive-baerian-phonotactics-notation#1]
I just came across this after seeing it used (albeit slightly modified) in [one of these articles in *Segments*](https://drive.google.com/file/d/1xGJnQDwDBiCETXPTMP1y8TXxCAQWrea-/view) and was intrigued. I was hoping to take a look at your .tex file to see how you built the notation so I wouldn't need to figure it out from scratch, but your [main.tex](https://github.com/LLBlumire/recursive-baerian-phonotactics-notation/blob/master/main.tex) file seems to be an empty file. Any chance you still happen to have that file lying around?

I'm also a bit curious how you'd approach more complex phonotactic scenarios, for example if there are *three* (or even more) potential choices instead of two. Would you just keep stacking the options vertically?

Thanks!

**Comment by LLBlumire** [comment]
Fixed now

**Comment by nai888** [comment]
Wonderful, thanks!
